# Gradle properties
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-8.0.482.8-hotspot
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G -Xms1G -XX:+UseG1GC
org.gradle.parallel=false
org.gradle.caching=false

# Encoding
systemProp.file.encoding=utf-8

# Forge specific
forgeVersion=1.8.9-11.15.1.2318-1.8.9
mcpVersion=stable_22
